#! /bin/bash
#$Author: ee364a11 $
#$Date: 2014-09-01 17:03:21 -0400 (Mon, 01 Sep 2014) $
#$Revision: 68284 $
#$HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/F14/students/ee364a11/Prelab01/test $
#$Id: test 68284 2014-09-01 21:03:21Z ee364a11 $

Price=0.99
echo 'Price: $0.99'

Pi=3.14159
printf "Pi: %1.2f\n" ${Pi}

printf "%5s\n" String_Var

echo "${HOME}"
echo '${HOME}'

printf "%s\n" $USER
printf "%15s\n" $SHELL
echo They said, "Hello, World."
echo "$0"

exit 0